name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.18.4", "1.19.0-rc.0"]
        otp: ["27.3.4"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Install dependencies
        run: mix deps.get
      - name: Compile (warnings as errors)
        run: MIX_ENV=test mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
      - name: Run Dialyzer
        run: mix dialyzer 