name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.18.4, 1.19.0-rc.0]
        otp: [27.3.4]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.elixir }}-${{ matrix.otp }}-
            ${{ runner.os }}-build-
      
      - name: Cache Dialyzer PLT
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/dialyxir_erlang-${{ matrix.otp }}_elixir-${{ matrix.elixir }}.plt
            ~/.cache/dialyxir_erlang-${{ matrix.otp }}_elixir-${{ matrix.elixir }}_deps-dev.plt
          key: ${{ runner.os }}-dialyxir-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-dialyxir-${{ matrix.otp }}-${{ matrix.elixir }}-
            ${{ runner.os }}-dialyxir-${{ matrix.otp }}-
            ${{ runner.os }}-dialyxir-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Compile (warnings as errors)
        run: MIX_ENV=test mix compile --warnings-as-errors
      
      - name: Run tests
        run: mix test
      
      - name: Run Dialyzer
        run: mix dialyzer 